In [9]:
import cv2 
import os
import mediapipe as mp
import numpy as np

In [7]:
cd frame

/Users/richardpark/Desktop/video/frame


In [16]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_holistic = mp.solutions.holistic

In [22]:
import natsort

imgfile_path = '/Users/richardpark/Desktop/video/frame'
IMAGE_FILES = os.listdir(imgfile_path)
IMAGE_FILES = natsort.natsorted(IMAGE_FILES)

In [23]:
IMAGE_FILES

['.DS_Store',
 'frame0.jpg',
 'frame1.jpg',
 'frame2.jpg',
 'frame3.jpg',
 'frame4.jpg',
 'frame5.jpg',
 'frame6.jpg',
 'frame7.jpg',
 'frame8.jpg',
 'frame9.jpg',
 'frame10.jpg',
 'frame11.jpg',
 'frame12.jpg',
 'frame13.jpg',
 'frame14.jpg',
 'frame15.jpg',
 'frame16.jpg',
 'frame17.jpg',
 'frame18.jpg',
 'frame19.jpg',
 'frame20.jpg',
 'frame21.jpg',
 'frame22.jpg',
 'frame23.jpg',
 'frame24.jpg',
 'frame25.jpg',
 'frame26.jpg',
 'frame27.jpg',
 'frame28.jpg',
 'frame29.jpg',
 'frame30.jpg',
 'frame31.jpg',
 'frame32.jpg',
 'frame33.jpg',
 'frame34.jpg',
 'frame35.jpg',
 'frame36.jpg',
 'frame37.jpg',
 'frame38.jpg',
 'frame39.jpg',
 'frame40.jpg',
 'frame41.jpg',
 'frame42.jpg',
 'frame43.jpg',
 'frame44.jpg',
 'frame45.jpg',
 'frame46.jpg',
 'frame47.jpg',
 'frame48.jpg',
 'frame49.jpg',
 'frame50.jpg',
 'frame51.jpg',
 'frame52.jpg',
 'frame53.jpg',
 'frame54.jpg',
 'frame55.jpg',
 'frame56.jpg',
 'frame57.jpg',
 'frame58.jpg',
 'frame59.jpg',
 'frame60.jpg',
 'frame61.jpg',
 'fr

In [25]:
# for idx, file in enumerate(IMAGE_FILES):
#     print(file)
#     if file == '.DS_Store':
#         continue
#     img = cv2.imread(file)
#     print(img)

In [ ]:
with mp_holistic.Holistic(static_image_mode=True, model_complexity=2, enable_segmentation=True, refine_face_landmarks=True) as holistic:
    for idx, file in enumerate(IMAGE_FILES):
        if file == '.DS_Store':
            continue
        img = cv2.imread(file)
        image_height, image_width, _ = img.shape
        
        # convert the BGR image to RGB before processing
        results = holistic.process(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        
        if results.pose_landmarks:
            print(
                f'Nose coordinates : ('
                f'{results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].x * image_width}, '
                f'{results.pose_landmarks.landmark[mp_holistic.PoseLandmark.NOSE].y * image_height})'
            )
        
        annotated_image = img.copy()
        
        # Draw segmentation on the image.
        # To improve segmentation around boundaries, consider applying a joint
        # bilateral filter to "results.segmentation_mask" with "image".
        condition = np.stack((results.segmentation_mask,) * 3, axis=-1) > 0.1
        # bg_image = np.zeros(img.shape, dtype=np.uint8)
        # bg_image[:] = BG_COLOR
        # annotated_image = np.where(condition, annotated_image)
        # Draw pose, left and right hands, and face landmarks on the image.
        mp_drawing.draw_landmarks(
            annotated_image,
            results.face_landmarks,
            mp_holistic.FACEMESH_TESSELATION,
            landmark_drawing_spec=None,
            connection_drawing_spec=mp_drawing_styles.get_default_face_mesh_tesselation_style())
        mp_drawing.draw_landmarks(
            annotated_image,
            results.pose_landmarks,
            mp_holistic.POSE_CONNECTIONS,
            landmark_drawing_spec=mp_drawing_styles.get_default_pose_landmarks_style())
        mp_drawing.draw_landmarks(
            annotated_image,
            results.left_hand_landmarks,
            mp_holistic.HAND_CONNECTIONS,
            landmark_drawing_spec=mp_drawing_styles.get_default_hand_landmarks_style()
        )
        mp_drawing.draw_landmarks(
            annotated_image,
            results.right_hand_landmarks,
            mp_holistic.HAND_CONNECTIONS,
            landmark_drawing_spec=mp_drawing_styles.get_default_hand_landmarks_style()
        )
        cv2.imwrite('/Users/richardpark/Desktop/video/frame_with_sklt/annotated_image' + str(idx) + '.png', annotated_image)
        # Plot pose world landmarks.
        # mp_drawing.plot_landmarks(
        #     results.pose_world_landmarks, mp_holistic.POSE_CONNECTIONS
        # )


In [35]:
ls

[K-Fancam] 레드벨벳 아이린 직캠 Feel My Rhythm (Red Velvet IRENE Fancam) l @MusicBank 220325.mp4
frame/
frame_to_video/
frame_with_sklt/


In [58]:
cd frame_with_sklt

/Users/richardpark/Desktop/video/frame_with_sklt


In [59]:
SKLT_IMAGE_PATH = '/Users/richardpark/Desktop/video/frame_with_sklt'
SKLT_IMAGE_FILES = os.listdir(SKLT_IMAGE_FILE)
SKLT_IMAGE_FILES = natsort.natsorted(SKLT_IMAGE_FILES)

In [60]:
SKLT_IMAGE_FILES

['annotated_image1.png',
 'annotated_image2.png',
 'annotated_image3.png',
 'annotated_image4.png',
 'annotated_image5.png',
 'annotated_image6.png',
 'annotated_image7.png',
 'annotated_image8.png',
 'annotated_image9.png',
 'annotated_image10.png',
 'annotated_image11.png',
 'annotated_image12.png',
 'annotated_image13.png',
 'annotated_image14.png',
 'annotated_image15.png',
 'annotated_image16.png',
 'annotated_image17.png',
 'annotated_image18.png',
 'annotated_image19.png',
 'annotated_image20.png',
 'annotated_image21.png',
 'annotated_image22.png',
 'annotated_image23.png',
 'annotated_image24.png',
 'annotated_image25.png',
 'annotated_image26.png',
 'annotated_image27.png',
 'annotated_image28.png',
 'annotated_image29.png',
 'annotated_image30.png',
 'annotated_image31.png',
 'annotated_image32.png',
 'annotated_image33.png',
 'annotated_image34.png',
 'annotated_image35.png',
 'annotated_image36.png',
 'annotated_image37.png',
 'annotated_image38.png',
 'annotated_image39.p

In [61]:
for i in SKLT_IMAGE_FILES:
    img = cv2.imread(i)
    print(img)

[[[254 199 194]
  [254 199 194]
  [254 199 194]
  ...
  [ 88  10  17]
  [ 81   4  11]
  [ 77   0   7]]

 [[254 199 194]
  [254 199 194]
  [254 199 194]
  ...
  [ 79   1   8]
  [ 72   0   2]
  [ 78   1   8]]

 [[254 199 194]
  [254 199 194]
  [255 200 195]
  ...
  [ 74   0   4]
  [ 75   0   5]
  [ 78   0   8]]

 ...

 [[255 156 159]
  [255 157 160]
  [255 159 159]
  ...
  [150  44  27]
  [149  43  26]
  [149  43  26]]

 [[255 155 157]
  [255 156 158]
  [253 157 157]
  ...
  [150  44  27]
  [149  43  26]
  [149  43  26]]

 [[253 154 156]
  [253 154 156]
  [251 155 155]
  ...
  [150  44  27]
  [149  43  26]
  [149  43  26]]]
[[[254 199 194]
  [254 199 194]
  [254 199 194]
  ...
  [ 86   9  16]
  [ 77   3   9]
  [ 74   0   6]]

 [[254 199 194]
  [254 199 194]
  [254 199 194]
  ...
  [ 77   0   7]
  [ 72   0   4]
  [ 75   1   7]]

 [[254 199 194]
  [254 199 194]
  [255 200 195]
  ...
  [ 71   0   1]
  [ 77   0   7]
  [ 76   0   6]]

 ...

 [[255 156 159]
  [255 157 160]
  [255 159 159]
  ..

KeyboardInterrupt: 

In [55]:
for idx, file in enumerate(SKLT_IMAGE_FILES):
    if file == '.DS_Store':
        continue
    
    img = cv2.imread(file)
    print(img)
    if img == None:
        continue
    
    height, width, layers = img.shape

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


In [65]:
import cv2
from tqdm import tqdm

In [68]:
def frame_to_video(skeleton_image_files):
    frame_array = []
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    fps = 30
    
    for idx, file in tqdm(enumerate(SKLT_IMAGE_FILES), total=len(SKLT_IMAGE_FILES)):
        if file == '.DS_Store':
            continue
    
        img = cv2.imread(file)
        height, width, layers = img.shape
        size = (width, height)
        frame_array.append(img)
    out = cv2.VideoWriter('/Users/richardpark/Desktop/video/frame_to_video/video.avi',fourcc, fps, size)
    for i in range(len(frame_array)):
        out.write(frame_array[i])
    
    cv2.destroyAllWindows()
    out.release()

In [69]:
frame_to_video(SKLT_IMAGE_FILES)

100%|██████████| 631/631 [00:04<00:00, 136.51it/s]
